<?php
/**
 * Created by PhpStorm.
 * User: melon
 * Date: 1/15/16
 * Time: 8:27 PM
 */

namespace database\seeds;

use App\Model\Country;
use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class CountryTableSeeder extends Seeder
{
    public function run()
    {
        Model::unguard();
        $countries = [
            array('name' => 'Afghanistan', 'code' => 'AFG', 'abbreviation' => 'AF'),
            array('name' => 'Albania', 'code' => 'ALB', 'abbreviation' => 'AL'),
            array('name' => 'Algeria', 'code' => 'DZA', 'abbreviation' => 'DZ'),
            array('name' => 'American Samoa', 'code' => 'ASM', 'abbreviation' => 'AS'),
            array('name' => 'Andorra', 'code' => 'AND', 'abbreviation' => 'AD'),
            array('name' => 'Angola', 'code' => 'AGO', 'abbreviation' => 'AO'),
            array('name' => 'Anguilla', 'code' => 'AIA', 'abbreviation' => 'AI'),
            array('name' => 'Antarctica', 'code' => 'ATA', 'abbreviation' => 'AQ'),
            array('name' => 'Antigua and Barbuda', 'code' => 'ATG', 'abbreviation' => 'AG'),
            array('name' => 'Argentina', 'code' => 'ARG', 'abbreviation' => 'AR'),
            array('name' => 'Armenia', 'code' => 'ARM', 'abbreviation' => 'AM'),
            array('name' => 'Aruba', 'code' => 'ABW', 'abbreviation' => 'AW'),
            array('name' => 'Australia', 'code' => 'AUS', 'abbreviation' => 'AU'),
            array('name' => 'Austria', 'code' => 'AUT', 'abbreviation' => 'AT'),
            array('name' => 'Azerbaijan', 'code' => 'AZE', 'abbreviation' => 'AZ'),
            array('name' => 'Bahamas', 'code' => 'BHS', 'abbreviation' => 'BS'),
            array('name' => 'Bahrain', 'code' => 'BHR', 'abbreviation' => 'BH'),
            array('name' => 'Bangladesh', 'code' => 'BGD', 'abbreviation' => 'BD'),
            array('name' => 'Barbados', 'code' => 'BRB', 'abbreviation' => 'BB'),
            array('name' => 'Belarus', 'code' => 'BLR', 'abbreviation' => 'BY'),
            array('name' => 'Belgium', 'code' => 'BEL', 'abbreviation' => 'BE'),
            array('name' => 'Belize', 'code' => 'BLZ', 'abbreviation' => 'BZ'),
            array('name' => 'Benin', 'code' => 'BEN', 'abbreviation' => 'BJ'),
            array('name' => 'Bermuda', 'code' => 'BMU', 'abbreviation' => 'BM'),
            array('name' => 'Bhutan', 'code' => 'BTN', 'abbreviation' => 'BT'),
            array('name' => 'Bolivia', 'code' => 'BOL', 'abbreviation' => 'BO'),
            array('name' => 'Bosnia-Herzegovina', 'code' => 'BIH', 'abbreviation' => 'BA'),
            array('name' => 'Botswana', 'code' => 'BWA', 'abbreviation' => 'BW'),
            array('name' => 'Bouvet Island', 'code' => 'BVT', 'abbreviation' => 'BV'),
            array('name' => 'Brazil', 'code' => 'BRA', 'abbreviation' => 'BR'),
            array('name' => 'British Indian Ocean Territory', 'code' => 'IOT', 'abbreviation' => 'IO'),
            array('name' => 'Brunei Darussalam', 'code' => 'BRN', 'abbreviation' => 'BN'),
            array('name' => 'Bulgaria', 'code' => 'BGR', 'abbreviation' => 'BG'),
            array('name' => 'Burkina Faso', 'code' => 'BFA', 'abbreviation' => 'BF'),
            array('name' => 'Burundi', 'code' => 'BDI', 'abbreviation' => 'BI'),
            array('name' => 'Cambodia', 'code' => 'KHM', 'abbreviation' => 'KH'),
            array('name' => 'Cameroon', 'code' => 'CMR', 'abbreviation' => 'CM'),
            array('name' => 'Canada', 'code' => 'CAN', 'abbreviation' => 'CA'),
            array('name' => 'Cape Verde', 'code' => 'CPV', 'abbreviation' => 'CV'),
            array('name' => 'Cayman Islands', 'code' => 'CYM', 'abbreviation' => 'KY'),
            array('name' => 'Central African Republic', 'code' => 'CAF', 'abbreviation' => 'CF'),
            array('name' => 'Chad', 'code' => 'TCD', 'abbreviation' => 'TD'),
            array('name' => 'Chile', 'code' => 'CHL', 'abbreviation' => 'CL'),
            array('name' => 'China', 'code' => 'CHN', 'abbreviation' => 'CN'),
            array('name' => 'Christmas Island', 'code' => 'CXR', 'abbreviation' => 'CX'),
            array('name' => 'Cocos (Keeling) Islands', 'code' => 'CCK', 'abbreviation' => 'CC'),
            array('name' => 'Colombia', 'code' => 'COL', 'abbreviation' => 'CO'),
            array('name' => 'Comoros', 'code' => 'COM', 'abbreviation' => 'KM'),
            array('name' => 'Congo', 'code' => 'COG', 'abbreviation' => 'CG'),
            array('name' => 'Congo, Democratic Republic of', 'code' => 'COD', 'abbreviation' => 'CD'),
            array('name' => 'Cook Islands', 'code' => 'COK', 'abbreviation' => 'CK'),
            array('name' => 'Costa Rica', 'code' => 'CRI', 'abbreviation' => 'CR'),
            array('name' => 'Cote D\'Ivoire', 'code' => 'CIV', 'abbreviation' => 'CI'),
            array('name' => 'Croatia (Hrvatska)', 'code' => 'HRV', 'abbreviation' => 'HR'),
            array('name' => 'Cuba', 'code' => 'CUB', 'abbreviation' => 'CU'),
            array('name' => 'Cyprus', 'code' => 'CYP', 'abbreviation' => 'CY'),
            array('name' => 'Czech Republic', 'code' => 'CZE', 'abbreviation' => 'CZ'),
            array('name' => 'Denmark', 'code' => 'DNK', 'abbreviation' => 'DK'),
            array('name' => 'Djibouti', 'code' => 'DJI', 'abbreviation' => 'DJ'),
            array('name' => 'Dominica', 'code' => 'DMA', 'abbreviation' => 'DM'),
            array('name' => 'Dominican Republic', 'code' => 'DOM', 'abbreviation' => 'DO'),
            array('name' => 'East Timor', 'code' => 'TMP', 'abbreviation' => 'TP'),
            array('name' => 'Ecuador', 'code' => 'ECU', 'abbreviation' => 'EC'),
            array('name' => 'Egypt', 'code' => 'EGY', 'abbreviation' => 'EG'),
            array('name' => 'El Salvador', 'code' => 'SLV', 'abbreviation' => 'SV'),
            array('name' => 'Equatorial Guinea', 'code' => 'GNQ', 'abbreviation' => 'GQ'),
            array('name' => 'Eritrea', 'code' => 'ERI', 'abbreviation' => 'ER'),
            array('name' => 'Estonia', 'code' => 'EST', 'abbreviation' => 'EE'),
            array('name' => 'Ethiopia', 'code' => 'ETH', 'abbreviation' => 'ET'),
            array('name' => 'Falkland Islands (Malvinas)', 'code' => 'FLK', 'abbreviation' => 'FK'),
            array('name' => 'Faroe Islands', 'code' => 'FRO', 'abbreviation' => 'FO'),
            array('name' => 'Fiji', 'code' => 'FJI', 'abbreviation' => 'FJ'),
            array('name' => 'Finland', 'code' => 'FIN', 'abbreviation' => 'FI'),
            array('name' => 'France', 'code' => 'FRA', 'abbreviation' => 'FR'),
            array('name' => 'French Guiana', 'code' => 'GUF', 'abbreviation' => 'GF'),
            array('name' => 'French Polynesia', 'code' => 'PYF', 'abbreviation' => 'PF'),
            array('name' => 'French Southern Territories', 'code' => 'ATF', 'abbreviation' => 'TF'),
            array('name' => 'Gabon', 'code' => 'GAB', 'abbreviation' => 'GA'),
            array('name' => 'Gambia', 'code' => 'GMB', 'abbreviation' => 'GM'),
            array('name' => 'Georgia', 'code' => 'GEO', 'abbreviation' => 'GE'),
            array('name' => 'Germany', 'code' => 'DEU', 'abbreviation' => 'DE'),
            array('name' => 'Ghana', 'code' => 'GHA', 'abbreviation' => 'GH'),
            array('name' => 'Gibraltar', 'code' => 'GIB', 'abbreviation' => 'GI'),
            array('name' => 'Great Britain (England, Scotland, Wales)', 'code' => 'GBR', 'abbreviation' => 'GB'),
            array('name' => 'Greece', 'code' => 'GRC', 'abbreviation' => 'GR'),
            array('name' => 'Greenland', 'code' => 'GRL', 'abbreviation' => 'GL'),
            array('name' => 'Grenada', 'code' => 'GRD', 'abbreviation' => 'GD'),
            array('name' => 'Guadeloupe', 'code' => 'GLP', 'abbreviation' => 'GP'),
            array('name' => 'Guam', 'code' => 'GUM', 'abbreviation' => 'GU'),
            array('name' => 'Guatemala', 'code' => 'GTM', 'abbreviation' => 'GT'),
            array('name' => 'Guinea', 'code' => 'GIN', 'abbreviation' => 'GN'),
            array('name' => 'Guinea-Bissau', 'code' => 'GNB', 'abbreviation' => 'GW'),
            array('name' => 'Guyana', 'code' => 'GUY', 'abbreviation' => 'GY'),
            array('name' => 'Haiti', 'code' => 'HTI', 'abbreviation' => 'HT'),
            array('name' => 'Heard Island and McDonald Islands', 'code' => 'HMD', 'abbreviation' => 'HM'),
            array('name' => 'Honduras', 'code' => 'HND', 'abbreviation' => 'HN'),
            array('name' => 'Hong Kong SAR of PRC', 'code' => 'HKG', 'abbreviation' => 'HK'),
            array('name' => 'Hungary', 'code' => 'HUN', 'abbreviation' => 'HU'),
            array('name' => 'Iceland', 'code' => 'ISL', 'abbreviation' => 'IS'),
            array('name' => 'India', 'code' => 'IND', 'abbreviation' => 'IN'),
            array('name' => 'Indonesia', 'code' => 'IDN', 'abbreviation' => 'ID'),
            array('name' => 'Iran', 'code' => 'IRN', 'abbreviation' => 'IR'),
            array('name' => 'Iraq', 'code' => 'IRQ', 'abbreviation' => 'IQ'),
            array('name' => 'Ireland', 'code' => 'IRL', 'abbreviation' => 'IE'),
            array('name' => 'Israel', 'code' => 'ISR', 'abbreviation' => 'IL'),
            array('name' => 'Italy', 'code' => 'ITA', 'abbreviation' => 'IT'),
            array('name' => 'Jamaica', 'code' => 'JAM', 'abbreviation' => 'JM'),
            array('name' => 'Japan', 'code' => 'JPN', 'abbreviation' => 'JP'),
            array('name' => 'Jordan', 'code' => 'JOR', 'abbreviation' => 'JO'),
            array('name' => 'Kazakhstan', 'code' => 'KAZ', 'abbreviation' => 'KZ'),
            array('name' => 'Kenya', 'code' => 'KEN', 'abbreviation' => 'KE'),
            array('name' => 'Kiribati', 'code' => 'KIR', 'abbreviation' => 'KI'),
            array('name' => 'Republic of Korea (South Korea)', 'code' => 'KOR', 'abbreviation' => 'KR'),
            array('name' => 'Korea, Democratic People\'s Republic (North Korea)', 'code' => 'PRK', 'abbreviation' => 'KP'),
            array('name' => 'Kosovo', 'code' => 'UNK', 'abbreviation' => 'XK'),
            array('name' => 'Kuwait', 'code' => 'KWT', 'abbreviation' => 'KW'),
            array('name' => 'Kyrgyzstan', 'code' => 'KGZ', 'abbreviation' => 'KG'),
            array('name' => 'Lao People\'s Democratic Republic', 'code' => 'LAO', 'abbreviation' => 'LA'),
            array('name' => 'Latvia', 'code' => 'LVA', 'abbreviation' => 'LV'),
            array('name' => 'Lebanon', 'code' => 'LBN', 'abbreviation' => 'LB'),
            array('name' => 'Lesotho', 'code' => 'LSO', 'abbreviation' => 'LS'),
            array('name' => 'Liberia', 'code' => 'LBR', 'abbreviation' => 'LR'),
            array('name' => 'Libyan Arab Jamahiriya', 'code' => 'LBY', 'abbreviation' => 'LY'),
            array('name' => 'Liechtenstein', 'code' => 'LIE', 'abbreviation' => 'LI'),
            array('name' => 'Lithuania', 'code' => 'LTU', 'abbreviation' => 'LT'),
            array('name' => 'Luxembourg', 'code' => 'LUX', 'abbreviation' => 'LU'),
            array('name' => 'Macao SAR of PRC (Macau)', 'code' => 'MAC', 'abbreviation' => 'MO'),
            array('name' => 'Macedonia', 'code' => 'MKD', 'abbreviation' => 'MK'),
            array('name' => 'Madagascar', 'code' => 'MDG', 'abbreviation' => 'MG'),
            array('name' => 'Malawi', 'code' => 'MWI', 'abbreviation' => 'MW'),
            array('name' => 'Malaysia', 'code' => 'MYS', 'abbreviation' => 'MY'),
            array('name' => 'Maldives', 'code' => 'MDV', 'abbreviation' => 'MV'),
            array('name' => 'Mali', 'code' => 'MLI', 'abbreviation' => 'ML'),
            array('name' => 'Malta', 'code' => 'MLT', 'abbreviation' => 'MT'),
            array('name' => 'Marshall Islands', 'code' => 'MHL', 'abbreviation' => 'MH'),
            array('name' => 'Martinique', 'code' => 'MTQ', 'abbreviation' => 'MQ'),
            array('name' => 'Mauritania', 'code' => 'MRT', 'abbreviation' => 'MR'),
            array('name' => 'Mauritius', 'code' => 'MUS', 'abbreviation' => 'MU'),
            array('name' => 'Mayotte', 'code' => 'MYT', 'abbreviation' => 'YT'),
            array('name' => 'Mexico', 'code' => 'MEX', 'abbreviation' => 'MX'),
            array('name' => 'Micronesia, Federated States of', 'code' => 'FSM', 'abbreviation' => 'FM'),
            array('name' => 'Monaco', 'code' => 'MCO', 'abbreviation' => 'MC'),
            array('name' => 'Mongolia', 'code' => 'MNG', 'abbreviation' => 'MN'),
            array('name' => 'Montenegro', 'code' => 'MNE', 'abbreviation' => 'ME'),
            array('name' => 'Montserrat', 'code' => 'MSR', 'abbreviation' => 'MS'),
            array('name' => 'Morocco', 'code' => 'MAR', 'abbreviation' => 'MA'),
            array('name' => 'Mozambique', 'code' => 'MOZ', 'abbreviation' => 'MZ'),
            array('name' => 'Myanmar', 'code' => 'MMR', 'abbreviation' => 'MM'),
            array('name' => 'Namibia', 'code' => 'NAM', 'abbreviation' => 'NA'),
            array('name' => 'Nauru', 'code' => 'NRU', 'abbreviation' => 'NR'),
            array('name' => 'Nepal', 'code' => 'NPL', 'abbreviation' => 'NP'),
            array('name' => 'Netherlands', 'code' => 'NLD', 'abbreviation' => 'NL'),
            array('name' => 'Netherlands Antilles', 'code' => 'ANT', 'abbreviation' => 'AN'),
            array('name' => 'New Caledonia', 'code' => 'NCL', 'abbreviation' => 'NC'),
            array('name' => 'New Zealand', 'code' => 'NZL', 'abbreviation' => 'NZ'),
            array('name' => 'Nicaragua', 'code' => 'NIC', 'abbreviation' => 'NI'),
            array('name' => 'Niger', 'code' => 'NER', 'abbreviation' => 'NE'),
            array('name' => 'Nigeria', 'code' => 'NGA', 'abbreviation' => 'NG'),
            array('name' => 'Niue', 'code' => 'NIU', 'abbreviation' => 'NU'),
            array('name' => 'Norfolk Island', 'code' => 'NFK', 'abbreviation' => 'NF'),
            array('name' => 'Northern Mariana Islands', 'code' => 'MNP', 'abbreviation' => 'MP'),
            array('name' => 'Norway', 'code' => 'NOR', 'abbreviation' => 'NO'),
            array('name' => 'Oman', 'code' => 'OMN', 'abbreviation' => 'OM'),
            array('name' => 'Pakistan', 'code' => 'PAK', 'abbreviation' => 'PK'),
            array('name' => 'Palau', 'code' => 'PLW', 'abbreviation' => 'PW'),
            array('name' => 'Panama', 'code' => 'PAN', 'abbreviation' => 'PA'),
            array('name' => 'Papua New Guinea', 'code' => 'PNG', 'abbreviation' => 'PG'),
            array('name' => 'Paraguay', 'code' => 'PRY', 'abbreviation' => 'PY'),
            array('name' => 'Peru', 'code' => 'PER', 'abbreviation' => 'PE'),
            array('name' => 'Philippines', 'code' => 'PHL', 'abbreviation' => 'PH'),
            array('name' => 'Pitcairn', 'code' => 'PCN', 'abbreviation' => 'PN'),
            array('name' => 'Poland', 'code' => 'POL', 'abbreviation' => 'PL'),
            array('name' => 'Portugal', 'code' => 'PRT', 'abbreviation' => 'PT'),
            array('name' => 'Puerto Rico', 'code' => 'PRI', 'abbreviation' => 'PR'),
            array('name' => 'Qatar', 'code' => 'QAT', 'abbreviation' => 'QA'),
            array('name' => 'Republic of Moldova', 'code' => 'MDA', 'abbreviation' => 'MD'),
            array('name' => 'Reunion', 'code' => 'REU', 'abbreviation' => 'RE'),
            array('name' => 'Romania', 'code' => 'ROM', 'abbreviation' => 'RO'),
            array('name' => 'Russia', 'code' => 'RUS', 'abbreviation' => 'RU'),
            array('name' => 'Rwanda', 'code' => 'RWA', 'abbreviation' => 'RW'),
            array('name' => 'Saint Helena', 'code' => 'SHN', 'abbreviation' => 'SH'),
            array('name' => 'Saint Kitts and Nevis', 'code' => 'KNA', 'abbreviation' => 'KN'),
            array('name' => 'Saint Lucia', 'code' => 'LCA', 'abbreviation' => 'LC'),
            array('name' => 'Saint Pierre and Miquelon', 'code' => 'SPM', 'abbreviation' => 'PM'),
            array('name' => 'Saint Vincent and the Grenadines', 'code' => 'VCT', 'abbreviation' => 'VC'),
            array('name' => 'Samoa', 'code' => 'WSM', 'abbreviation' => 'WS'),
            array('name' => 'San Marino', 'code' => 'SMR', 'abbreviation' => 'SM'),
            array('name' => 'Sao Tome and Principe', 'code' => 'STP', 'abbreviation' => 'ST'),
            array('name' => 'Saudi Arabia', 'code' => 'SAU', 'abbreviation' => 'SA'),
            array('name' => 'Senegal', 'code' => 'SEN', 'abbreviation' => 'SN'),
            array('name' => 'Serbia', 'code' => 'SRB', 'abbreviation' => 'RS'),
            array('name' => 'Seychelles', 'code' => 'SYC', 'abbreviation' => 'SC'),
            array('name' => 'Sierra Leone', 'code' => 'SLE', 'abbreviation' => 'SL'),
            array('name' => 'Singapore', 'code' => 'SGP', 'abbreviation' => 'SG'),
            array('name' => 'Slovakia', 'code' => 'SVK', 'abbreviation' => 'SK'),
            array('name' => 'Slovenia', 'code' => 'SVN', 'abbreviation' => 'SI'),
            array('name' => 'Solomon Islands', 'code' => 'SLB', 'abbreviation' => 'SB'),
            array('name' => 'Somalia', 'code' => 'SOM', 'abbreviation' => 'SO'),
            array('name' => 'South Africa', 'code' => 'ZAF', 'abbreviation' => 'ZA'),
            array('name' => 'South Georgia and South Sandwich Islands', 'code' => 'SGS', 'abbreviation' => 'GS'),
            array('name' => 'Spain', 'code' => 'ESP', 'abbreviation' => 'ES'),
            array('name' => 'Sri Lanka', 'code' => 'LKA', 'abbreviation' => 'LK'),
            array('name' => 'Sudan', 'code' => 'SDN', 'abbreviation' => 'SD'),
            array('name' => 'Suriname', 'code' => 'SUR', 'abbreviation' => 'SR'),
            array('name' => 'Svalbard and Jan Mayen', 'code' => 'SJM', 'abbreviation' => 'SJ'),
            array('name' => 'Swaziland', 'code' => 'SWZ', 'abbreviation' => 'SZ'),
            array('name' => 'Sweden', 'code' => 'SWE', 'abbreviation' => 'SE'),
            array('name' => 'Switzerland', 'code' => 'CHE', 'abbreviation' => 'CH'),
            array('name' => 'Syria', 'code' => 'SYR', 'abbreviation' => 'SY'),
            array('name' => 'Taiwan', 'code' => 'TWN', 'abbreviation' => 'TW'),
            array('name' => 'Tajikistan', 'code' => 'TJK', 'abbreviation' => 'TJ'),
            array('name' => 'Tanzania, United Republic of', 'code' => 'TZA', 'abbreviation' => 'TZ'),
            array('name' => 'Thailand', 'code' => 'THA', 'abbreviation' => 'TH'),
            array('name' => 'Togo', 'code' => 'TGO', 'abbreviation' => 'TG'),
            array('name' => 'Tokelau', 'code' => 'TKL', 'abbreviation' => 'TK'),
            array('name' => 'Tonga', 'code' => 'TON', 'abbreviation' => 'TO'),
            array('name' => 'Trinidad and Tobago', 'code' => 'TTE', 'abbreviation' => 'TT'),
            array('name' => 'Tunisia', 'code' => 'TUN', 'abbreviation' => 'TN'),
            array('name' => 'Turkey', 'code' => 'TUR', 'abbreviation' => 'TR'),
            array('name' => 'Turkmenistan', 'code' => 'TKM', 'abbreviation' => 'TM'),
            array('name' => 'Turks and Caicos Islands', 'code' => 'TCA', 'abbreviation' => 'TC'),
            array('name' => 'Tuvalu', 'code' => 'TUV', 'abbreviation' => 'TV'),
            array('name' => 'Uganda', 'code' => 'UGA', 'abbreviation' => 'UG'),
            array('name' => 'Ukraine', 'code' => 'UKR', 'abbreviation' => 'UA'),
            array('name' => 'United Arab Emirates', 'code' => 'ARE', 'abbreviation' => 'AE'),
            array('name' => 'United States', 'code' => 'USA', 'abbreviation' => 'US'),
            array('name' => 'United States Minor Outlying Islands', 'code' => 'UMI', 'abbreviation' => 'UM'),
            array('name' => 'Uruguay', 'code' => 'URY', 'abbreviation' => 'UY'),
            array('name' => 'Uzbekistan', 'code' => 'UZB', 'abbreviation' => 'UZ'),
            array('name' => 'Vanuatu', 'code' => 'VUT', 'abbreviation' => 'VU'),
            array('name' => 'Vatican City State', 'code' => 'VAT', 'abbreviation' => 'VA'),
            array('name' => 'Venezuela', 'code' => 'VEN', 'abbreviation' => 'VE'),
            array('name' => 'Vietnam', 'code' => 'VNM', 'abbreviation' => 'VN'),
            array('name' => 'Virgin Islands (UK)', 'code' => 'VGB', 'abbreviation' => 'VG'),
            array('name' => 'Virgin Islands (US)', 'code' => 'VIR', 'abbreviation' => 'VI'),
            array('name' => 'Wallis and Futuna', 'code' => 'WLF', 'abbreviation' => 'WF'),
            array('name' => 'Western Sahara', 'code' => 'ESH', 'abbreviation' => 'EH'),
            array('name' => 'Yemen', 'code' => 'YEM', 'abbreviation' => 'YE'),
            array('name' => 'Zambia', 'code' => 'ZMB', 'abbreviation' => 'ZM'),
            array('name' => 'Zimbabwe', 'code' => 'ZWE', 'abbreviation' => 'ZW'),
        ];
        foreach ($countries as $country) {
            Country::create($country);
        }
    }
}
