notifications:
  slack:
    secure: n+iMNg8JMaKKrrylXm6o/plV7jKc9aprfd9mFGdZSwvvcTLGeetGmUnR29UYLL5gX6kITQW5QdAE67mI/aTiUOuCmgWcPVyPzbLQg7fCFyeFfC2zAwm2ku9xLjsyzAKCSA0DQ9DGgND1FyN5S/Zuy9k8W1ISpt6ZHeMaj4Go3n4n+sf8QvpDYGkr06i3qm8lo42SPIgIpV41CjZC16KHuKZz7BbQZz1z8fCJ0SBy8J8S/opYNKsnrFMPNlJgs6TlwEZEG7xMkxfiMg9fjDBQ+44vrEofWLexjSFXrbhQxX7deoSg3HvfPnBNH+aT2PpYHdKVSRAikbWYmuxxnYWCyXf4VfLAi46dhmPVzRHZOC+CkO1Cj7qAcH6itXB/Qg3P1abX5zJzViskheb/ZQ9ZsqqaXvRWwgyxIh86ORK87jP5UxeaHFjuCViOwJVnxiCZ9k6a1iJSXuJNslTZhiE3UMwMd6838IyGLQdD/l3RxR48O9zvoLo7RcMYgodX4b4GaquXe9RLcIR8Tx8FRDvbkmHQg1075Dm1T+DFVa56KnALkUKfpGsQjBzgYcfaa4spQJlhpIpxuIUJMUHeUI46Jww47OKrO+9CvN4dYCX0ImR4glsAQS/SWIRnjabvn5XvW3T+X97pdRqzUhlv4K6JGah1tUk5JITIqGusbvIP1Yw=
language: php
sudo: required
os:
  - linux
php:
  - 7.0
  - 7.1
services:
  - mysql
  - redis-server
addons:
  mariadb: 10.1
before_install:
  - mysql -e "create database IF NOT EXISTS orm_core;" -uroot
  - mysql -e "grant all on orm_core.* to 'travis'@'localhost';" -uroot
  - mysql -e "FLUSH PRIVILEGES;" -uroot
  - cp .env.travis .env
install:
  - composer self-update
  - composer install --no-interaction
before_script:
  - php artisan key:generate
  - php artisan orm:bckey
  - bash generate_jwt_key.sh
  - php artisan migrate
  - php artisan route:cache
  - php artisan api:cache
  - cat .env
script:
  - composer test
