language: php
php:
  - '5.6'
  - '7.0'
  - nightly
services:
  - mysql
  - redis-server
addons:
  mariadb: '10.1'
before_install:
  - mysql -e "create database IF NOT EXISTS slerp_core;" -uroot
  - mysql -e "grant all on slerp_core.* to 'travis'@'localhost';" -uroot
  - mysql -e "FLUSH PRIVILEGES;" -uroot
install:
  - composer self-update
  - composer install --no-interaction
before_script:
  - cp .env.travis .env
  - php artisan key:generate
  - bash generate_jwt_key.sh
  - php artisan migrate
script:
  - vendor/bin/phpunit --verbose --debug
